on:
  workflow_call

jobs:
  run-tests-artifact:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: zip the artifact
        run: tar -zcvf /tmp/theartifact.tgz ./ && mv /tmp/theartifact.tgz ./
      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: theartifact
          path: theartifact.tgz
      - name: Delay the workflow
        run: sleep 5m
